/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 02 17:38:49 GMT 2018
 */

package aps;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import aps.HexToOct;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class HexToOct_ESTest extends HexToOct_ESTest_scaffolding {

  @Test
  public void test0()  throws Throwable  {
      int int0 = HexToOct.hex2decimal("");
      assertEquals(0, int0);
  }

  @Test
  public void test1()  throws Throwable  {
      int int0 = HexToOct.hex2decimal("~Xs=3\"f*D<*$6");
      assertEquals((-16978186), int0);
  }

  @Test
  public void test2()  throws Throwable  {
      int int0 = HexToOct.decimal2octal((-185426102));
      assertEquals(0, int0);
  }

  @Test
  public void test3()  throws Throwable  {
      int int0 = HexToOct.decimal2octal(1861152495);
      assertEquals((-185426102), int0);
  }

  @Test
  public void test4()  throws Throwable  {
      int int0 = HexToOct.decimal2octal(19);
      assertEquals(23, int0);
  }

  @Test
  public void test5()  throws Throwable  {
      // Undeclared exception!
      try { 
        HexToOct.hex2decimal((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         assertThrownBy("aps.HexToOct", e);
      }
  }

  @Test
  public void test6()  throws Throwable  {
      HexToOct hexToOct0 = new HexToOct();
  }

  @Test
  public void test7()  throws Throwable  {
      SystemInUtil.addInputLine("<I#gb.Yz2@)?9GI");
      String[] stringArray0 = new String[1];
      HexToOct.main(stringArray0);
  }

  @Test
  public void test8()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        HexToOct.main(stringArray0);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         assertThrownBy("java.util.Scanner", e);
      }
  }

  @Test
  public void test9()  throws Throwable  {
      int int0 = HexToOct.hex2decimal("Y\"\":7,kqTjU`");
      assertEquals(1861152495, int0);
  }
}
